name: Build App
on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '3.1.301'
      
      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run: dotnet build --no-restore -c Release
