name: Deploy .net Application
on:
    push:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
          - name: Download Build Artifacts
            uses: actions/download-artifact@v3
            with:
              name: test-repo-artifact
        

