name: Deploy .net Application
on:
    push:
    workflow_call:

jobs:
   
 deploy:
      name: deploy
      runs-on: ubuntu-latest
      needs: build
      steps:
       - name: Download Build Artifacts
         uses: actions/download-artifact@v3
        with:
          name: test-repo-artifact