name: Sequential workflow

on:
    push:
    workflow_dispatch:
    workflow_call:    

jobs:

    job-A:
        runs-on: ubuntu-latest
        steps:
            - name: step 1
              run: echo "Relax for 15 mins"

            - name: step 2
              run: echo "Take a nap for 30 mins"

    job-B:
        runs-on: ubuntu-latest
        needs: job-A
        steps:
            - name: step 1
              run: echo "Relax for 5 mins"

            - name: step 2

              run: echo "sleep for 65 mins"